package com.truckspot.utils


const val PREFERENCE_NAME = "TruckSpot"
const val PREF_LOGGED_IN = "PREF_LOGGED_IN"
const val PREF_USERNAME = "USERNAME"
const val PREF_PASSWORD = "PREF_PASSWORD"
const val PREF_TOKEN = "PREF_TOKEN"
const val PREF_NAME = "PREF_NAME"
const val PREF_LAST_LOG_TIME = "LAST_LOG_TIME"
const val PREF_CURRENT_MODE = "CURRENT_MODE"
const val PREF_SHIPPING_NUMBER = "PREF_SHIPPING_NUMBER"
const val PREF_TRAILER_NO = "PREF_TRAILER_NO"


